# Generated by Django 3.2.10 on 2022-02-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_filemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemessage',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'application/pdf'), ('jpg', 'image/jpeg'), ('mp3', 'audio/mpeg')], max_length=10),
        ),
    ]
