# Generated by Django 3.1.7 on 2021-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_connectionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('online', 'On-line'), ('offline', 'Off-line')], default='online', max_length=10),
        ),
        migrations.DeleteModel(
            name='ConnectionHistory',
        ),
    ]
