# Generated by Django 3.2.10 on 2022-02-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_filemessage_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemessage',
            name='filename',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
