version: '3.7'

x-variables: &variables
  ENV_STAGE: dev
  USE_HTTPS: 0

services:
  nginx:
#    build:
#      context: .
#      dockerfile: docker/prod/nginx/Dockerfile
    ports:
      - "10000:10000"
  chat:
    environment:
      <<: *variables
  celery:
    command: celery -A src worker -l info -Q celery
    environment:
      <<: *variables

networks:
  microservice_network:
    name: dev_microservice_network
