apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatchart.fullname" . }}
  labels:
    {{- include "chatchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chatchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "chatchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chatchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: {{ .Values.chat.healthCheckUrl }}
              port: http
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 5
            httpGet:
              path: {{ .Values.chat.healthCheckUrl }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: chatchart-secrets
                  key: superUserEmail
                  optional: false
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chatchart-secrets
                  key: superUserPassword
                  optional: false
            - name: ENABLE_RENDERING
              value: {{ .Values.chat.enableRendering | quote }}
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chatchart-secrets
                  key: secretKey
                  optional: false
            - name: DJANGO_ALLOWED_HOSTS
              value: {{ required "chat allowed hosts is required" .Values.chat.allowedHosts | quote }}
            - name: POSTGRES_HOST
              value: {{ default (printf "%s-postgresql" .Release.Name) .Values.postgresql.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.chat.db.postgresPort | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresDatabase | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresPassword | quote }}
            - name: REDIS_HOST
              value: {{ default (printf "%s-redis-master" .Release.Name) .Values.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.chat.redis.redisPort | quote }}
            - name: REDIS_URL
              value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
            - name: REDIS_DB
              value: {{ .Values.chat.redis.redisDB | quote }}
            - name: DEBUG
              value: {{ .Values.chat.debug | quote }}
            - name: SITE_ID
              value: {{ .Values.chat.siteId | quote }}
            - name: SQL_ENGINE
              value: {{ .Values.chat.sqlEngine | quote }}
            - name: BACKEND_SITE
              value: {{ .Values.chat.backendSite| quote }}
            - name: ADMIN_URL
              value: {{ .Values.chat.adminUrl | quote }}
            - name: DJANGO_SETTINGS_MODULE
              value: {{ .Values.chat.djangoSettingsModule | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
