apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chatchart.fullname" . }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    {{- include "chatchart.labels" . | nindent 4 }}
spec:
{{- if .Values.persistentVolumeClaim.storageClassName }}
  storageClassName: {{ .Values.persistentVolumeClaim.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
